import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import globals from 'globals'

// Flat config: an array of config objects, applied in order. Each object can
// scope itself with `files`/`ignores`; later objects override earlier ones.
export default tseslint.config(
  {
    ignores: [
      '.wrangler/**',
      'dist/**',
      'node_modules/**',
      'worker-configuration.d.ts', // generated by `bun run cf-typegen`
    ],
  },
  js.configs.recommended, // base JS rules
  ...tseslint.configs.recommended, // TS parser + recommended TS rules
  {
    languageOptions: {
      // Worker runtime globals (fetch, Response, R2Bucket, ...) for src/,
      // plus Node globals (process, ...) for the upload scripts.
      globals: { ...globals.worker, ...globals.node },
    },
  },
)
