import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import globals from 'globals'

// Flat config: an array of config objects, applied in order. Each object can
// scope itself with `files`/`ignores`; later objects override earlier ones.
export default tseslint.config(
  {
    ignores: [
      '.wrangler/**',
      'dist/**',
      'drizzle/**', // generated migrations / introspected schema
      'node_modules/**',
      'worker-configuration.d.ts', // generated by `bun run cf-typegen`
    ],
  },
  js.configs.recommended, // base JS rules
  ...tseslint.configs.recommended, // TS parser + recommended TS rules
  // Worker sources: only Worker globals, so stray process/Buffer gets flagged.
  {
    files: ['src/**/*.ts'],
    languageOptions: { globals: globals.worker },
  },
  // Node-side tooling (upload scripts, drizzle config): Node globals.
  {
    files: ['scripts/**/*.ts', 'drizzle.config.ts'],
    languageOptions: { globals: globals.node },
  },
)
